#World
MAP_SIZE = 40
# % of terrain
FOREST_AMOUNT = 0.4
CAMPFIRE_AMOUNT = 0.03
WATER_AMOUNT = 0.10
PLAIN_AMOUNT = 0.47
#terrain ID
ID_FOREST = 1
ID_CAMPFIRE = 2
ID_WATER = 3
ID_PLAIN = 4
#respawn
# WOOD_REGEN = 8
# WOLF_REGEN = 10
# SHEEP_REGEN = 6
WOOD_MIN_SPAWN = 2
WOOD_MAX_SPAWN = 10

#Creatures
#human
#max stats
HUNGER_MAX = 100
THIRSTY_MAX = 100
ENERGY_MAX = 100
TEMP_MAX = 38
MAX_WOOD_INV = 20
#die at
TEMP_DIE = 34
HUNGER_DIE = 0
THIRSTY_DIE = 0
#water
THIRSTY_GAIN = 20
#energy gain
REST_ENERGY_GAIN = 15
CAMPFIRE_ENERGY_GAIN = 20
CAMPFIRE_TEMP_GAIN = 2
#loss per move
ENERGY_LOSS_PER_MOVE = 2
HUNGER_LOSS_PER_MOVE = 1
THIRSTY_LOSS_PER_MOVE = 1
TEMP_LOSS_PER_MOVE = 0.1
POINTS_PER_MOVE = 1
CHOP_TREE_ENERGY_COST = 5
#num of creature 
NUM_SHEEP = 40
NUM_WOLVES = 30
NUM_KNIGHTS = 20
# BABY = 1 TODO OR NOT
#base energy
HUMAN_START_ENERGY = 100
WOLF_START_ENERGY = 30
SHEEP_START_ENERGY = 0 
KNIGHT_START_ENERGY  = 60

#combat with wold
COMBAT_WOLF_HUNGER_GAIN = 20
COMBAT_WOLF_ENERGY_GAIN = -30
COMBAT_WOLF_POINTS_GAIN = 30
SHEEP_HUNGER_GAIN = 10
SHEEP_ENERGY_GAIN = -10
COMBAT_KNIGHT_HUNGER_GAIN = 0
COMBAT_KNIGHT_ENERGY_GAIN = -20
COMBAT_KNIGHT_POINTS_GAIN = 100

#movement
MAX_ACTIONS_PER_DAY = 15
#keys
ACTION_MOVE_UP = 0
ACTION_MOVE_DOWN = 1
ACTION_MOVE_LEFT = 2
ACTION_MOVE_RIGHT = 3
ACTION_STAY = 4
ACTION_INTERACT = 5


#model 
SEED = None
#musi byc nieparzysta
MODEL_VIEW = 11
BATCH_SIZE = 256
GAMMA = 0.99
LR = 0.0002
MEMORY_SIZE = 100000
EPS_START = 1.0
EPS_END = 0.05
EPS_DECAY = 150000
#ile razy gramy w gre od nowa
EPISODEDS = 6000
TARGET_UPDATE = 300

#train
DEATH_MAP = {
    "jedzenie": 0,
    "picie": 1,
    "temperatura": 2,
    "wilczek": 3,
    "rycerz": 4,
    "unknown": 5
}