#World
MAP_SIZE = 40
# % of terrain
FOREST_AMOUNT = 0.35
CAMPFIRE_AMOUNT = 0.05
WATER_AMOUNT = 0.10
PLAIN_AMOUNT = 0.5
#terrain ID
ID_FOREST = 0
ID_CAMPFIRE = 1
ID_WATER = 2
ID_PLAIN = 3
#respawn
WOOD_REGEN = 8
WOLF_REGEN = 10
SHEEP_REGEN = 6


#Creatures
#human
#max stats
HUNGER_MAX = 100
THIRSTY_MAX = 100
ENERGY_MAX = 100
TEMP_MAX = 38
MAX_WOOD_INV = 10
#die at
TEMP_DIE = 34
HUNGER_DIE = 0
THIRSTY_DIE = 0
#energy gain
REST_ENERGY_GAIN = 10
CAMPFIRE_ENERGY_GAIN = 10
CAMPFIRE_TEMP_GAIN = 1
#loss per move
ENERGY_LOSS_PER_MOVE = 5
HUNGER_LOSS_PER_MOVE = 1.0
THIRSTY_LOSS_PER_MOVE = 1
TEMP_LOSS_PER_MOVE = 0.1

CHOP_TREE_ENERGY_COST = 5
#num of creature 
NUM_SHEEP = 4
NUM_WOLVES = 3
NUM_KNIGHTS = 5
# BABY = 1 TODO OR NOT
#base energy
HUMAN_START_ENERGY = 100
WOLF_START_ENERGY = 20
SHEEP_START_ENERGY = 0 
KNIGHT_START_ENERGY  = 60

#combat with wold
COMBAT_WOLF_HUNGER_GAIN = 20
COMBAT_WOLF_ENERGY_GAIN = -30
SHEEP_HUNGER_GAIN = 10
SHEEP_ENERGY_GAIN = -10
COMBAT_KNIGHT_HUNGER_GAIN = 0
COMBAT_KNIGHT_ENERGY_GAIN = -20
#movement
MAX_ACTIONS_PER_DAY = 15
#keys
ACTION_MOVE_UP = 0
ACTION_MOVE_DOWN = 1
ACTION_MOVE_LEFT = 2
ACTION_MOVE_RIGHT = 3
ACTION_STAY = 4
ACTION_INTERACT = 5
#