#World
MAP_SIZE = 10
# % of terrain
FOREST_AMOUNT = 0.25
CAMPFIRE_AMOUNT = 0.25
WATER_AMOUNT = 0.25
PLAIN_AMOUNT = 0.25

#terrain ID
ID_FOREST = 0
ID_CAMPFIRE = 1
ID_WATER = 2
ID_PLAIN = 3

#respawn
WOOD_REGEN = 3
WOLF_REGEN = 3
SHEEP_REGEN = 3

#Creatures
#human
HUNGER = 1
THIRSTY = 1
TEMP_DOWN = 0.05
MAX_WOOD_INV = 5

#num of creature 
NUM_SHEEP = 4
NUM_WOLVES = 3
# BABY = 1 TODO OR NOT
#base energy
HUMAN_START_ENERGY = 100
#wolf
WOLF_START_ENERGY = 20
#sheep
SHEEP_START_ENERGY = 0 

#combat
COMBAT_HUNGER_GAIN = 20
COMBAT_ENERGY_GAIN = 20

#movement
ACTION_MOVE_UP = 0
ACTION_MOVE_DOWN = 1
ACTION_MOVE_LEFT = 2
ACTION_MOVE_RIGHT = 3
ACTION_STAY = 4
ACTION_INTERACT = 5
MAX_ACTIONS_PER_DAY = 20